# fly.toml app configuration file generated for stockscreener-backend on 2025-07-10T23:14:23+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stockscreener-backend'
primary_region = 'bom'

['env']
  DB_URL='DATABASE_URL=postgres://ketul:Vvm@2020@stockscreener-db.internal:5432/mydb?sslmode=disable'
  ENV='production'
  JWT_SECRET='azbycxdw1928374655'
  PORT='10001'
  REDIS_URL='rediss://default:AXCmAAIjcDFmYjJkNDU4MDdiZmI0MTk0OTk4N2MxZTMyMjI4ZDhhYXAxMA@amazing-moth-28838.upstash.io:6379'
  ALLOWED_ORIGINS='https://stockscreener-frontend.vercel.app/'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
