// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type JobTracker struct {
	ID           int32            `json:"id"`
	JobID        pgtype.UUID      `json:"job_id"`
	UserID       pgtype.UUID      `json:"user_id"`
	JobStatus    string           `json:"job_status"`
	JobCreatedAt pgtype.Timestamp `json:"job_created_at"`
	JobUpdatedAt pgtype.Timestamp `json:"job_updated_at"`
}

type Screener struct {
	ID            int32       `json:"id"`
	Name          string      `json:"name"`
	Rules         []byte      `json:"rules"`
	StockUniverse string      `json:"stock_universe"`
	UserID        pgtype.UUID `json:"user_id"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
}
