// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateJobTracker(ctx context.Context, arg CreateJobTrackerParams) (JobTracker, error)
	CreateScreener(ctx context.Context, arg CreateScreenerParams) (Screener, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteScreener(ctx context.Context, id int32) error
	GetJobTrackerByJobID(ctx context.Context, jobID pgtype.UUID) (JobTracker, error)
	GetJobTrackerByUserID(ctx context.Context, userID pgtype.UUID) (JobTracker, error)
	GetScreener(ctx context.Context, id int32) (Screener, error)
	GetScreeners(ctx context.Context, userID pgtype.UUID) ([]Screener, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	UpdateJobTrackerForExistingJob(ctx context.Context, arg UpdateJobTrackerForExistingJobParams) (JobTracker, error)
	UpdateJobTrackerForNewJob(ctx context.Context, arg UpdateJobTrackerForNewJobParams) (JobTracker, error)
	UpdateScreener(ctx context.Context, arg UpdateScreenerParams) (Screener, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
