// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: screeners.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScreener = `-- name: CreateScreener :one
INSERT INTO screeners (user_id, name, rules)
VALUES ($1, $2, $3)
RETURNING id, name, rules, stock_universe, user_id
`

type CreateScreenerParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Rules  []byte      `json:"rules"`
}

func (q *Queries) CreateScreener(ctx context.Context, arg CreateScreenerParams) (Screener, error) {
	row := q.db.QueryRow(ctx, createScreener, arg.UserID, arg.Name, arg.Rules)
	var i Screener
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rules,
		&i.StockUniverse,
		&i.UserID,
	)
	return i, err
}

const deleteScreener = `-- name: DeleteScreener :exec
DELETE FROM screeners
WHERE id = $1
`

func (q *Queries) DeleteScreener(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteScreener, id)
	return err
}

const getScreener = `-- name: GetScreener :one
SELECT id, name, rules, stock_universe, user_id FROM screeners
WHERE id = $1
`

func (q *Queries) GetScreener(ctx context.Context, id int32) (Screener, error) {
	row := q.db.QueryRow(ctx, getScreener, id)
	var i Screener
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rules,
		&i.StockUniverse,
		&i.UserID,
	)
	return i, err
}

const getScreeners = `-- name: GetScreeners :many
SELECT id, name, rules, stock_universe, user_id FROM screeners
WHERE user_id = $1
`

func (q *Queries) GetScreeners(ctx context.Context, userID pgtype.UUID) ([]Screener, error) {
	rows, err := q.db.Query(ctx, getScreeners, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Screener{}
	for rows.Next() {
		var i Screener
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rules,
			&i.StockUniverse,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScreener = `-- name: UpdateScreener :one
UPDATE screeners
SET name = $2, rules = $3, stock_universe = $4
WHERE id = $1
RETURNING id, name, rules, stock_universe, user_id
`

type UpdateScreenerParams struct {
	ID            int32  `json:"id"`
	Name          string `json:"name"`
	Rules         []byte `json:"rules"`
	StockUniverse string `json:"stock_universe"`
}

func (q *Queries) UpdateScreener(ctx context.Context, arg UpdateScreenerParams) (Screener, error) {
	row := q.db.QueryRow(ctx, updateScreener,
		arg.ID,
		arg.Name,
		arg.Rules,
		arg.StockUniverse,
	)
	var i Screener
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rules,
		&i.StockUniverse,
		&i.UserID,
	)
	return i, err
}
